apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-fss
  namespace: wordpress
provisioner: oracle.com/oci-fss
parameters:
  # Insert mount target from the FSS here
  mntTargetId: ocid1.mounttarget.oc1.ap_tokyo_1.aaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  # Mount TargetのOCIDに変更してください